Midproject
MSIA/2021-msia423--hakimi---ben--project pull request #1
Opened 2021-05-07 22:26 UTC by bhakimi21

Hey @stephengill5  

I've made the following changes to this MSIA 423 project repo:

- Added src/downloadSource.py to the repository. This module gets the raw excel files from sportsbookreviewonline.com and saves them to a local path which can be specified. It is called in the run.py module.

- Added src/upload.py to the repository. This module uploads data from a local directory to an S3 bucket and is called in the run.py module.

- Replaced src/add_songs.py with creatDB.py. This modifies and the original file and allows for the creation of a "Games" table in my msia423_db.db on RDS. Again, this module is called in the run.py module.

- Created/updated Dockerfile to build Docker Image.

- Modified the README.md file to help instruct users through the processes of acquiring and uploading various data to S3 and RDS.

- Updated requirements.txt to contain only relevant packages.

- Modified run.py to allow for database creation (createDB), as well as downloading and uploading data from the source to S3 (loadData). Inputs for the functions called in this module are configured using argparse and contain some mandatory and optional inputs.

- Raw data has been added to the data/external folder from the downloadSource.py module for use in the upload.py module.

- Removed unused/redundant lines of code.

If you could take a look at the modules in the src folder and make sure the loggers, commenting and general formatting look good that would be very helpful. Also, please try building the Docker Image with the command from the README.md (no need to run the other Docker commands if you don't want to). Finally, I trust your writing more than mine, so could you do a quick spell/grammar check on the README.md as well.

Thank you and don't forget to watch the beach volleyball tournament!
-Ben

2021-05-20 23:14 UTC, stephengill5 commented
Confirming that I was able to download/upload raw data without a hitch. I was also able to create the database after fixing that tiny typo in the README (change suggested in a comment). I mention this in a comment, but there's one case (`MYSQL_DATABASE` passed in, but not `SQLALCHEMY_DATABASE_URI`) where I don't think the code does quite what the documentation states.

2021-05-21 00:30 UTC, stephengill5 commented
You could maybe add some info or debug logging into `run.py`, it might help if new issues cropped up

2021-05-21 03:42 UTC, stephengill5 requested changes
Howdy @bhakimi21 🤠 

After looking everything over, running your code, and double-checking your documentation, I've made some specific comments and suggestions, and have some more general points of feedback as well. Here are some recapping points:

- I would try to make try/excepts more informative by breaking up the trys more and adding more specific except statements
- Not much of an issue since it's pretty quick to run through all your documentation, but it'd be fine/not too verbose if you added more logging, generally
- Double-check your requirements.txt, as I think there are some packages listed in there that aren't actually necessary (at least for the requirements file)
- Functionality: I outlined this in an earlier comment, and I'll paste that here: I was able to download/upload raw data without a hitch. I was also able to create the database after fixing that tiny typo in the README (change suggested in a comment). I mention this in a comment, but there's one case (MYSQL_DATABASE passed in, but not SQLALCHEMY_DATABASE_URI) where I don't think the code does quite what the documentation states; not an error, but saves to S3 instead of locally.
- Readability: These were highlighted in the line-by-line comments, but I don't think the functions you defined need to be nested , so I'd un-nest them. (This might fall under Design, but yeah.) It would definitely help readability. Also, your code is super efficient and straightforward, though it may be a bit easier to follow with a little more commenting (I'm talking mostly about `downloadSource.py`). But it is pretty straightforward, so not a big deal.
- Design: The code is broken up pretty well over all. As just noted, I think the class and function definitions shouldn't be nested in the couple of places they are. I also think you may want to break up your functions in `downloadSource` a bit (for example, maybe just make a little helper function to return a URL string from an input year integer, and have that be separate from `loaddata`), but sometimes I get overly-granular with my functions so just something to consider. The modularity of the code makes perfect sense, and there isn't any duplication. There are a few places where you could have variables be configured instead of hard-coded or used as inputs (particularly the input that is usually `.xlsx`).
- Documentation: Docstrings are placed everywhere they're needed. I suggested some tweaks in the line-by-line comments, but they're mostly just about adding a tiny bit of detail. As mentioned, I would maybe recommend adding a few more comments within the code, but it's not a huge deal currently. Aside from a small typo, the README is in good shape; I just added a few suggestions for the commands. Commit statements could be a little more specific (i.e. what part of the file was updated).

Lastly, I should note that I made sure to watch the beach volleyball tournament. Cal Poly was robbed.

Keep up the great work!
-Stephen

2021-05-21 03:42 UTC, stephengill5 commented on README.md
> +If no optional inputs are specified for the run.py function, the data the original data will be pulled from the internet and placed in the local path `data/data.csv`. It will then be uploaded to the
```suggestion
If no optional inputs are specified for the run.py function, the data will be pulled from the internet and placed in the local path `data/data.csv`. It will then be uploaded to the the S3 bucket `s3://2021-msia423-hakimi-ben/rawCSVUpload/raw.csv`. To change the S3 bucket (the 2021-msia423-hakimi-ben part of the previous path), input the desired name of your S3 bucket in the first argument after `loadData`. To change the name of the file when uploaded to S3 (the rawCSVUpload/raw.csv part of the previous path), input the desired file path in the second argument after `loadData`.
```

2021-05-21 18:21 UTC, bhakimi21 commented on README.md
> +docker run -e MYSQL_HOST -e MYSQL_PORT -e MYSQL_USER -e MYSQL_PASSWORD -e MYSQL_DATABSE -e SQLALCHEMY_DATABASE_URI nflgames run.py createDB
I think like 90% of my issues in programming are spelling related THANK YOU!

2021-05-21 19:08 UTC, merged